# paAIP2 Population Analysis

In [ ]:
# Configure Notebook width
from IPython.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [ ]:
# Import packages and modules
import os
import numpy as np

from Lab_Analyses.Population_Analysis import population_utilities as p_utils
from Lab_Analyses.Population_Analysis.preprocess_population_data import organize_population_data
from Lab_Analyses.Population_Analysis.paAIP2_population_analysis import paAIP2_population_analysis
from Lab_Analyses.Population_Analysis.paAIP2_population_plotting import plot_paAIP2_population_dynamics

%matplotlib inline

## Datasets

In [ ]:
# paAIP2 mouse ids
pa_1 = "JW156" # Not using due to missing session
pa_2 = "JW157"
pa_3 = "JW158"
pa_4 = "JW159"
pa_5 = "JW175"
pa_6 = "JW176"

pa_mice = [pa_2, pa_3, pa_4, pa_5, pa_6]

# EGFP mouse ids
gfp_1 = "JW196"
gfp_2 = "JW197"
gfp_3 = "JW198"
gfp_4 = "JW199"

gfp_mice = [gfp_1, gfp_2, gfp_3, gfp_4]
gfp_mice = [gfp_1, gfp_2, gfp_4]

## Analysis Parameters
roi_match = False
sensor = "RCaMP2"
zoom_factor = 2
reprocess = False
activity_window = (-1, 2)


## Preprocess data

In [ ]:
# paAIP2 mice
for mouse in pa_mice:
    organize_population_data(
        mouse_id=mouse,
        roi_match=roi_match,
        sensor=sensor,
        zoom_factor=zoom_factor,
        reprocess=True,
        save=True
    )
    
# EGFP mice
for mouse in gfp_mice:
    organize_population_data(
        mouse_id=mouse,
        roi_match=roi_match,
        sensor=sensor,
        zoom_factor=zoom_factor,
        reprocess=True,
        save=True
    )

## Analyze Population Data

In [ ]:
paAIP2_population_analysis(
    paAIP2_mice=pa_mice,
    EGFP_mice=gfp_mice,
    activity_window=activity_window,
    save_ind=True
)

## Visualize data

In [ ]:
# Load datasets
EGFP_data_list = p_utils.load_analyzed_pop_datasets(gfp_mice, "EGFP")
paAIP2_data_list = p_utils.load_analyzed_pop_datasets(pa_mice, "paAIP2")

figure_path = r"C:\Users\Jake\Desktop\Figures\grouped_data\paAIP2_Population\Activity"

In [ ]:
# Plot Activity Dynamics
plot_paAIP2_population_dynamics(
    EGFP_data_list,
    paAIP2_data_list,
    mvmt_only=True,
    norm=True,
    spikes=True,
    example_pa=None,
    example_gfp=None,
    figsize=(15,15),
    save=False,
    save_path=figure_path,
)

In [ ]:
# Plot some session traces
## Select data
data = paAIP2_data_list[1]
data = EGFP_data_list[0]

## Traces
traces = data.zscore_smooth_spikes[0]
mvmt = data.lever_active[0]
color = "mediumslateblue"

In [ ]:
import matplotlib.pyplot as plt
%matplotlib qt
save_path = r"C:\Users\Jake\Desktop\Figures\Examples\Example_images\coactivity_plasticity\Local_Coactivity\basal_stable"

x = np.arange(traces.shape[0]) / 30
fig, ax = plt.subplot_mosaic("""A""",figsize=(7,10))
title = "JW196_EGFP_Day_1"
# Randomly select 20 traces
#idxs = np.random.randint(low=0, high=traces.shape[1], size=20)
idxs = [0,1,2,3,4,5,6,7]
for j, i in enumerate(idxs):
    print(i)
    ax["A"].plot(x[:], traces[:, i] + j * 10, color=color, linewidth=.5)

In [ ]:
data.__dict__.keys()

In [1]:
from Lab_Analyses.Utilities.save_load_pickle import load_pickle
import os

In [2]:
path = r"G:\Analyzed_data\individual\JW157\population_data"
fname = "JW157_Early_population_data"
print(os.path.join(path, fname))
data = load_pickle([os.path.join(path, fname)])[0]

G:\Analyzed_data\individual\JW157\population_data\JW157_Early_population_data


In [3]:
data.__dict__.keys()

dict_keys(['mouse_id', 'session', 'date', 'imaging_parameters', 'time', 'lever_force_resample', 'lever_force_smooth', 'lever_velocity_envelop', 'lever_active', 'rewarded_movement_force', 'rewarded_movement_binary', 'binary_cue', 'reward_delivery', 'punish_delivery', 'cell_positions', 'fluorescence', 'dFoF', 'processed_dFoF', 'estimated_spikes', 'processed_estimated_spikes', 'activity_trace', 'floored_trace', 'movement_cells', 'silent_cells', 'reward_movement_cells', 'reward_silent_cells', 'movement_cells_spikes', 'silent_cells_spikes', 'reward_movement_cells_spikes', 'reward_silent_cells_spikes'])

In [7]:
import numpy as np
sname = "JW157_Early_population_spikes.npy"
load_spikes = np.load(os.path.join(path, sname))

In [98]:
# Plot some session traces
## Select data
dFoF = data.processed_dFoF
spikes = load_spikes.T
spikes = np.nan_to_num(spikes, nan=0)
#spikes = data.estimated_spikes

color_dFoF = "mediumslateblue"
color_spikes = "red"

In [25]:
import matplotlib.pyplot as plt
%matplotlib qt
save_path = r"C:\Users\Jake\Desktop\Figures\Examples\Example_images\coactivity_plasticity\Local_Coactivity\basal_stable"

x = np.arange(dFoF.shape[0]) / 30
fig, ax = plt.subplot_mosaic("""A""",figsize=(7,10))
title = "JW196_EGFP_Day_1"
# Randomly select 20 traces
idxs = np.random.randint(low=0, high=dFoF.shape[1], size=20)
for j, i in enumerate(idxs):
    print(i)
    #ax["A"].plot(x[:], dFoF[:, i] + j * 2, color="mediumslateblue", linewidth=.5)
    ax["A"].plot(x[:], spikes[:, i] + j * 0.2, color="red", linewidth=.5)

229
68
15
231
234
125
241
10
96
164
6
233
63
118
195
29
47
108
213
206


In [99]:
x = spikes[:, 2]
d = dFoF[:, 2]
active_x = np.zeros(len(x))
active_x[x > 0.2] = 1

In [101]:
pad = np.zeros(1)
diff = np.diff(np.concatenate((pad,active_x, pad)))

start = diff == 1
stop = diff == -1
start_idxs = np.nonzero(start)[0]
stop_idxs = np.nonzero(stop)[0]

deriv = np.gradient(x)

In [102]:
for i, j in zip(start_idxs, stop_idxs):
    print(f"{i} - {j}")

294 - 329
363 - 370
387 - 392
440 - 441
573 - 579
1192 - 1207
1268 - 1282
1374 - 1379
1391 - 1398
1407 - 1423
1457 - 1462
1581 - 1584
1866 - 1878
1906 - 1920
2126 - 2132
2498 - 2503
2526 - 2532
2574 - 2596
3141 - 3155
3209 - 3216
3496 - 3501
3516 - 3543
3557 - 3564
3663 - 3670
3685 - 3691
3716 - 3721
4045 - 4056
4081 - 4097
4145 - 4150
4195 - 4201
5321 - 5333
5456 - 5468
5553 - 5565
5591 - 5595
6184 - 6192
6646 - 6651
6671 - 6681
6705 - 6727
6930 - 6949
7477 - 7490
7540 - 7547
8606 - 8618
8670 - 8674
8871 - 8872
9500 - 9519
10119 - 10126
11251 - 11267
11329 - 11338
11367 - 11379
11985 - 12004
12031 - 12039
12592 - 12597
12619 - 12626
12875 - 12885
12978 - 12995
13279 - 13284
13345 - 13347
13483 - 13491
13632 - 13635
13808 - 13820
13838 - 13840
14209 - 14219
14572 - 14600
14694 - 14702
14861 - 14875
14987 - 15005
15012 - 15024
15469 - 15478
15491 - 15501
16263 - 16266
16565 - 16571
16590 - 16600
16732 - 16737
16784 - 16785
16875 - 16888
17231 - 17244
17546 - 17561
18261 - 18272
18285 - 

In [103]:
def refine_start_stop(start, stop, deriv, cutoff):
    # Refine start
    start_search = deriv[:start]
    below_cutoff = start_search <= cutoff
    new_start = np.nonzero(below_cutoff)[0][-1]
    # Refine stop
    stop_search = deriv[stop:]
    below_cutoff = stop_search >= -cutoff
    new_stop = np.nonzero(below_cutoff)[0][0] + stop
    
    return (new_start, new_stop)

In [104]:
transitions = []
for start, stop in zip(start_idxs, stop_idxs):
    trans = refine_start_stop(start, stop, deriv, cutoff=0.005)
    transitions.append(trans)
transitions

[(291, 336),
 (357, 377),
 (380, 400),
 (430, 448),
 (564, 584),
 (1187, 1213),
 (1261, 1288),
 (1366, 1381),
 (1388, 1402),
 (1402, 1429),
 (1445, 1469),
 (1571, 1590),
 (1859, 1883),
 (1900, 1924),
 (2118, 2139),
 (2491, 2514),
 (2520, 2539),
 (2565, 2604),
 (3132, 3163),
 (3202, 3222),
 (3486, 3508),
 (3510, 3548),
 (3550, 3572),
 (3653, 3675),
 (3676, 3693),
 (3714, 3731),
 (4037, 4066),
 (4075, 4103),
 (4137, 4156),
 (4182, 4208),
 (5315, 5338),
 (5438, 5473),
 (5546, 5573),
 (5581, 5603),
 (6176, 6198),
 (6636, 6656),
 (6664, 6688),
 (6696, 6735),
 (6921, 6958),
 (7469, 7498),
 (7531, 7557),
 (8598, 8621),
 (8662, 8684),
 (8857, 8880),
 (9490, 9530),
 (10110, 10133),
 (11243, 11274),
 (11324, 11346),
 (11360, 11387),
 (11980, 12005),
 (12022, 12045),
 (12579, 12605),
 (12609, 12629),
 (12866, 12894),
 (12970, 13003),
 (13267, 13291),
 (13340, 13356),
 (13473, 13495),
 (13623, 13645),
 (13801, 13824),
 (13828, 13851),
 (14198, 14226),
 (14565, 14613),
 (14685, 14708),
 (14855, 148

In [105]:
refined_active = np.zeros(len(active_x))
for trans in transitions:
    refined_active[trans[0]: trans[1]] = 1
    
floored = np.copy(x)
inactive_idxs = np.nonzero(refined_active == 0)[0]
print(inactive_idxs)
floored[inactive_idxs] = 0
print(x)
print(floored)

[    0     1     2 ... 48201 48202 48203]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]


In [100]:
plt.plot(d)
plt.plot(x)
#plt.plot(active_x)
plt.plot(refined_active)

In [106]:
plt.plot(x)
plt.plot(floored)

In [93]:
np.nansum(x)

1383.7189632270738